---
# tasks file for python-check-requirements
- name: Wait until apt is not blocked
  become: yes
  shell: if [[ -e $(cat /var/lib/dpkg/lock) ]]; then while [[ -n $(cat /var/lib/dpkg/lock) ]]; do sleep 5; done; fi
  when:
    ansible_os_family == "Debian"

- name: Check pip is installed anywhere but CentOS
  package: name=python-pip state=present
  become: True
  when: ansible_os_family != "RedHat"

- name: Check pip is installed in CentOS
  shell: 'curl https://bootstrap.pypa.io/get-pip.py | sudo python -'
  become: True
  when: ansible_os_family == "RedHat"

- name: Check virtualenv is installed
  pip: name=virtualenv state=present
  become: True
  when: virtualenv is defined

- name: Upgrade pip
  pip: name=pip extra_args='--upgrade' virtualenv={{virtualenv}}
  become: True
  when: virtualenv is defined

- name: Check the requirements in the specified virtualenv
  pip: requirements={{requirements_file}} virtualenv={{virtualenv}}
  become: True
  when: virtualenv is defined

- name: Check the requirements globally
  pip: requirements={{requirements_file}}
  when: virtualenv is undefined
  become: true
